version: 2
updates:
  # npm packages (example)
  - package-ecosystem: "npm"
    directory: "/" # location of package.json
    schedule:
      interval: "weekly" # "daily", "weekly", or "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
    assignees:
      - "suicide"

  # GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
